version: "3.1"

services:
  postgres:
    env_file:
      - ./config/.env
    build: ./db
    user: ${POSTGRES_USER}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./db:/var/lib/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    build: ./app/server
    volumes:
      - ./app/server:/server
    env_file:
      - ./config/.env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${HOST_DB}:${PG_PORT}/${POSTGRES_DB}
    ports:
      - "${API_PORT}:3001"
    depends_on:
      postgres:
        condition: service_healthy

  client:
    build: ./app/client
    volumes:
      - ./app/client:/client
    env_file:
      - ./config/.env
    ports:
      - "${PORT}:3000"
    depends_on:
      - server
